In [1]:
import pandas as pd
df=pd.read_csv("C:\\Users\\adhil\\OneDrive\\Desktop\\pandasworks\\world_famous_places\\world_famous_places_2024.csv")

In [11]:
df.head(3)

,Place_Name,Country,City,Annual_Visitors_Millions,Type,UNESCO_World_Heritage,Year_Built,Entry_Fee_USD,Best_Visit_Month,Region,Tourism_Revenue_Million_USD,Average_Visit_Duration_Hours,Famous_For
0,Eiffel Tower,France,Paris,7.0,Monument/Tower,No,1889,35,May-June/Sept-Oct,Western Europe,95,2.5,"Iconic iron lattice tower, symbol of Paris"
1,Times Square,United States,New York City,50.0,Urban Landmark,No,1904,0,Apr-June/Sept-Nov,North America,70,1.5,"Bright lights, Broadway shows, New Year's Eve ..."
2,Louvre Museum,France,Paris,8.7,Museum,Yes,1793,22,Oct-March,Western Europe,120,4.0,"World's most visited museum, home to Mona Lisa"

In [12]:
df.isnull().sum()

Place_Name                      0
Country                         0
City                            0
Annual_Visitors_Millions        0
Type                            0
UNESCO_World_Heritage           0
Year_Built                      0
Entry_Fee_USD                   0
Best_Visit_Month                0
Region                          0
Tourism_Revenue_Million_USD     0
Average_Visit_Duration_Hours    0
Famous_For                      0
dtype: int64

In [13]:
df.columns

Index(['Place_Name', 'Country', 'City', 'Annual_Visitors_Millions', 'Type',
       'UNESCO_World_Heritage', 'Year_Built', 'Entry_Fee_USD',
       'Best_Visit_Month', 'Region', 'Tourism_Revenue_Million_USD',
       'Average_Visit_Duration_Hours', 'Famous_For'],
      dtype='object')

In [8]:
#  Top 5 most visited places
df.sort_values(by="Annual_Visitors_Millions", ascending=False).head(5).sort_index()

,Place_Name,Country,City,Annual_Visitors_Millions,Type,UNESCO_World_Heritage,Year_Built,Entry_Fee_USD,Best_Visit_Month,Region,Tourism_Revenue_Million_USD,Average_Visit_Duration_Hours,Famous_For
1,Times Square,United States,New York City,50.0,Urban Landmark,No,1904,0,Apr-June/Sept-Nov,North America,70,1.5,"Bright lights, Broadway shows, New Year's Eve ..."
12,Central Park,United States,New York City,42.0,Park,No,1857,0,May-Sept,North America,35,3.0,Urban park oasis in Manhattan
13,Las Vegas Strip,United States,Las Vegas,41.7,Entertainment District,No,1905,0,March-May/Sept-Nov,North America,6800,8.0,"Casino resorts, entertainment, nightlife"
18,Disneyland (California),United States,Anaheim,16.0,Theme Park,No,1955,104,Apr-May/Sept-Nov,North America,3200,8.0,Original Disney theme park
19,Magic Kingdom (Orlando),United States,Orlando,17.0,Theme Park,No,1971,109,Jan-May/Sept-Dec,North America,4500,10.0,Disney World's flagship park with Cinderella C...

In [ ]:
# Which region has the most visitors
df.groupby("Region")["Annual_Visitors_Millions"].sum()

Region
East Asia           19.00
Middle East          6.00
North Africa         2.80
North America      205.10
Oceania              8.20
South America        3.70
South Asia           7.50
Southeast Asia       2.60
Southern Europe     21.35
Western Europe      63.70
Name: Annual_Visitors_Millions, dtype: float64

In [ ]:
# highest tourist revenue
df.sort_values(by="Tourism_Revenue_Million_USD", ascending=False).head()

,Place_Name,Country,City,Annual_Visitors_Millions,Type,UNESCO_World_Heritage,Year_Built,Entry_Fee_USD,Best_Visit_Month,Region,Tourism_Revenue_Million_USD,Average_Visit_Duration_Hours,Famous_For
13,Las Vegas Strip,United States,Las Vegas,41.7,Entertainment District,No,1905,0,March-May/Sept-Nov,North America,6800,8.0,"Casino resorts, entertainment, nightlife"
19,Magic Kingdom (Orlando),United States,Orlando,17.0,Theme Park,No,1971,109,Jan-May/Sept-Dec,North America,4500,10.0,Disney World's flagship park with Cinderella C...
18,Disneyland (California),United States,Anaheim,16.0,Theme Park,No,1955,104,Apr-May/Sept-Nov,North America,3200,8.0,Original Disney theme park
20,Grand Canyon,United States,Arizona,6.0,Natural Wonder,Yes,Natural Formation,35,March-May/Sept-Nov,North America,780,5.0,Massive canyon carved by Colorado River
25,Burj Khalifa,United Arab Emirates,Dubai,6.0,Skyscraper,No,2010,45,Nov-March,Middle East,350,2.0,Tallest building in the world